//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: login.proto
namespace mw
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"C2S_LoginReq")]
  public partial class C2S_LoginReq : global::ProtoBuf.IExtensible
  {
    public C2S_LoginReq() {}
    
    private string _deviceID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"deviceID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string deviceID
    {
      get { return _deviceID; }
      set { _deviceID = value; }
    }
    private string _platformID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"platformID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string platformID
    {
      get { return _platformID; }
      set { _platformID = value; }
    }

    private EClientType _clientType = EClientType.Android;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"clientType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(EClientType.Android)]
    public EClientType clientType
    {
      get { return _clientType; }
      set { _clientType = value; }
    }
    private EPlatformType _platformType;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"platformType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public EPlatformType platformType
    {
      get { return _platformType; }
      set { _platformType = value; }
    }

    private string _session = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"session", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string session
    {
      get { return _session; }
      set { _session = value; }
    }
    //private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { 
      // modified by zeta.
      //return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing);
      return null;
      }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"S2C_LoginACK")]
  public partial class S2C_LoginACK : global::ProtoBuf.IExtensible
  {
    public S2C_LoginACK() {}
    
    private int _errCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"errCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int errCode
    {
      get { return _errCode; }
      set { _errCode = value; }
    }
    private int _sessionID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"sessionID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int sessionID
    {
      get { return _sessionID; }
      set { _sessionID = value; }
    }
    private int _serverTime;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"serverTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int serverTime
    {
      get { return _serverTime; }
      set { _serverTime = value; }
    }
    //private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { 
      // modified by zeta.
      //return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing);
      return null;
      }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"C2S_CreateReq")]
  public partial class C2S_CreateReq : global::ProtoBuf.IExtensible
  {
    public C2S_CreateReq() {}
    
    private string _roleName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roleName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string roleName
    {
      get { return _roleName; }
      set { _roleName = value; }
    }

    private int _jobId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"jobId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int jobId
    {
      get { return _jobId; }
      set { _jobId = value; }
    }
    //private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { 
      // modified by zeta.
      //return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing);
      return null;
      }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"EClientType")]
    public enum EClientType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Web", Value=1)]
      Web = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"iOS", Value=2)]
      iOS = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Android", Value=3)]
      Android = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"EPlatformType")]
    public enum EPlatformType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Gfan", Value=1)]
      Gfan = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NineOne", Value=2)]
      NineOne = 2
    }
  
}