//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: pkgid.proto
namespace mw
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"S2C_CommonError")]
  public partial class S2C_CommonError : global::ProtoBuf.IExtensible
  {
    public S2C_CommonError() {}
    
    private EErrorNo _error;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"error", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public EErrorNo error
    {
      get { return _error; }
      set { _error = value; }
    }
    //private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { 
      // modified by zeta.
      //return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing);
      return null;
      }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"C2SPKGID")]
    public enum C2SPKGID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"C2S_LOGIN_REQ", Value=1)]
      C2S_LOGIN_REQ = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"C2S_CREATE_REQ", Value=2)]
      C2S_CREATE_REQ = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"S2CPKGID")]
    public enum S2CPKGID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"S2C_COMMON_ERROR", Value=255)]
      S2C_COMMON_ERROR = 255,
            
      [global::ProtoBuf.ProtoEnum(Name=@"S2C_LOGIN_ACK", Value=254)]
      S2C_LOGIN_ACK = 254,
            
      [global::ProtoBuf.ProtoEnum(Name=@"S2C_ROLE_INFO_NTF", Value=253)]
      S2C_ROLE_INFO_NTF = 253
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"EErrorNo")]
    public enum EErrorNo
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_SUCESS", Value=0)]
      ERR_SUCESS = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SYS_ERROR", Value=1)]
      SYS_ERROR = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_SYS_ERR", Value=2)]
      LOGIN_SYS_ERR = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_PWD_ERR", Value=3)]
      LOGIN_PWD_ERR = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_CHECK_ING", Value=4)]
      LOGIN_CHECK_ING = 4
    }
  
}